### ISSUE TITLE
执行最后一步python test_video.py -L 48 --grid后总是报错ModuleNotFoundError: No module named 'configs'

### ISSUE THREAD

**Issue by mingda27** [arceus-jia/SocialBook-AnimateAnyone#1]
我试了好几次，都是这个问题，不知道是不是缺少哪个包？
File "D:\ProgramAI\Github-app\SocialBook\AnimateAnyone\script\test_video.py", line 29, in <module> 
from configs.prompts.test_cases import TestCasesDict
ModuleNotFoundError: No module named 'configs'

**Comment by arceus-jia** [comment]
首先确保下submodule 有没有用正确被clone下来， 就是SocialBook-AnimateAnyone/Moore-AnimateAnyone下面有没有东西。当初是不是用 git clone git@github.com:arceus-jia/SocialBook-AnimateAnyone.git --recursive 来clone的。
如果没有的话需要clone一下我fork的改版的 https://github.com/arceus-jia/Moore-AnimateAnyone 

另外这一行确实不需要了我回头删一下

**Comment by mingda27** [comment]
确实是Moore-AnimateAnyone下面没有文件的原因。我刚开始安装时直接下载的zip，没有使用git clone，再下载个你说的https://github.com/arceus-jia/Moore-AnimateAnyone，然后解压后放进去就可以了。最终成功运行了。

**Comment by mingda27** [comment]
确实是Moore-AnimateAnyone下面没有文件的原因。我刚开始安装时直接下载的zip，没有使用git clone，再下载个你说的https://github.com/arceus-jia/Moore-AnimateAnyone，然后解压后放进去就可以了。最终成功运行了。

**Comment by mingda27** [comment]
确实是Moore-AnimateAnyone下面没有文件的原因，我刚开始安装时直接下载的zip，没有使用git clone。解决方法是，下载个你说的Moore-AnimateAnyone的zip压缩包，然后解压后复制进去就可以了。最终成功运行了。
